const teams = [
  "Aalborg BK", "Aarau", "Aarhus", "AB", "Aberdeen", "Académica Coimbra", "Admira Wien", "Admira Wacker", "ADO Den Haag",
  "AE Larisas", "AEK Athīna", "AEK Làrnaka", "AEL Lemesos", "AIK Solna", "Ajax", "Akademik Sofija", "Alanija Vladikavkaz",
  "Alaskert", "Álaves", "Alemannia Aachen", "Hamburger", "Amsterdam FC", "Anderlecht", "Anorthōsī Ammochōstou", "Royal Antwerp", 
  "Anži Machačkala", "Apoel", "Apollon Limassol", "Ararat", "Ards", "Arges Pitesti", "Aris Bonnevoie", "Arīs Limassol", 
  "Aris Salonicco", "Arsenal", "Astana", "Asteras Tripolīs", "Aston Villa", "Astra Giurgiu", "Atalanta", "Athletic Bilbao", 
  "Athlone Town", "Atlético Madrid", "Atvidaberg", "Austria Wien", "Auxerre", "Avenir Beggen", "AZ Alkmaar", "B1903", "B1909", 
  "B1913", "Ballkani", "Banik Ostrava", "Barcelona", "Basilea", "Bastia", "BATE Borisov", "Bayer Leverkusen", "Bayern München", 
  "Beitar Gerusalemme ", "Belenenses", "Benfica", "Beroe", "Beşiktaş", "Beveren", "Birmingham City", "BK Frem", "Blackburn Rovers", 
  "Boavista", "Bochum", "Bodø/Glimt", "Bohemians", "Bohemians Praga", "Bologna", "Bolton", "Bordeaux", "Borussia Dortmund", "Borussia M'Gladbach", 
  "Botev Plovdiv", "Braga", "Brage", "Brann", "Brasov FC", "Breidablik", "Brighton", "Brøndby", "Burnley", "Bursaspor", "Cagliari", "Cannes", 
  "Carl Zeiss Jena", "Celta Vigo", "Celtic", "CFR Cluj", "Chaves", "Chelsea", "Chemnitzer", "Club Brugge", "Coleraine", "Köln", "Kjøbenhavns BK", 
  "Cork Celtic", "Cork City", "Cork Hibernians", "Čornomorec' Odesa", "Corvinul Hunedoara", "Crusaders", "Csepel", "CSKA Mosca", "CSKA Sofija", 
  "CUF Barreiro", "Cukaricki", "DAC Dunajská Streda", "Debrecen", "Denizlispor", "Deportivo La Coruña", "Derby County", "Derry City", 
  "Dinamo Berlin", "Dinamo București", "Dynamo Dresden", "Dinamo Kiev", "Dinamo Minsk", "Dinamo Mosca", "Dinamo Tbilisi", "Dinamo Tirana", 
  "Dinamo Zagreb", "Diosgyor", "Djurgården", "Dnipro", "Dnipro-1", "DOS Utrecht", "Drumcondra", "Duisburgo", "Dukla Praha", "Dundalk", 
  "Dundee FC", "Dundee Utd", "DWS", "Dyskobolia Grodzisk", "Eendracht Aalst", "Eintracht Braunschweig", "Eintracht Frankfurt", 
  "Elbasani", "Elfsborg", "EPA Larnaca", "Erzgebirge Aue", "Esbjerg", "Espanyol", "Estoril Praia", "Etar", "Everton", "FC Jazz", "Fehérvár", 
  "Fenerbahçe", "Ferencváros", "Feyenoord", "Fiorentina", "First Vienna", "FK TSC Bačka Topola", "Flamurtari", "Flora Tallin", "Floriana", "Fortuna Dusseldorf", 
  "Fram Reykjavik", "Fredrikstad", "Freiburg", "Fulham", "Galatasaray", "Gaziantepspor", "Gençlerbirliği", "Genk", "Genoa", "Gent", "Getafe", 
  "GKS Katowice", "Glenavon", "Glentoran", "Górnik Zabrze", "Göteborg", "Grasshoppers", "Grazer AK", "Groningen", "Guingamp", "Gwardia Warszawa", 
  "Győr", "Haarlem", "Häcken", "Hajduk Split", "Haka", "Halmstad", "Hammarby", "Hamrun Spartans", "Hannover 96", "Hansa Rostock", "Hapoel Be'er Sheva", 
  "Hapoel Tel Aviv", "Heart of Midlothian", "Heerenveen", "Hellas Verona", "Helsingborg", "Hertha Berliner", "Hibernian", "Hibernians", "HIFK", "HJK", "Hoffenheim ", 
  "Honvéd Budapest", "HPS", "Hradec Králové", "Hvidovre", "IA Akraness", "IBV Vestmannæyja", "IFK Malmö", "Ilves", "Internazionale Milano", "Inter Bratislava", "Ipswich Town", 
  "Ironi Kiryat Shmona", "Istanbul Basaksehir", "Jablonec", "Jeunesse Esch", "Juventus", "KA Akureyri", "Kaiserslautern", "Karlsruher", "Karpaty", "KB", 
  "Keflavík", "KF Tiranë", "Kí Klaksvík", "Kilmarnock", "Køge BK", "Kongsvinger IT", "Konyaspor", "KPV", "KR Reykjavík", "Krasnodar ", "KSV Waregem", 
  "Kuban' Krasnodar", "KuPS", "Kuusysi", "KV Mechelen", "La Chaux-de-Fonds", "Las Palmas", "LASK", "Laval", "Lazio", "Lech Poznań", "Leeds United", 
  "Legia Warszawa", "Leicester City", "Lens", "Levante", "Levski Sofija", "Lierse", "Lille", "Lillestrøm", "Limerick", "Lincoln Red Imps", "Linfield", "Linz", 
  "Lisburn Distillery", "Liteks Loveč", "Liverpool", "Livorno", "Łódzki", "Lokeren", "Lokomotiv Leipzig", "Lokomotiv Moskva", "Lokomotiv Sofija", 
  "Lausanne", "Luzern", "Ludogorec", "Lugano", "Lyn Oslo", "Lyngby", "Maccabi Haifa", "Maccabi Tel Aviv", "Magdeburg", "Mainz", "Mallorca", "Málaga", "Malmö FF", 
  "Manchester City", "Manchester United", "Marek Dupnica", 
  "Marítimo", "Metalist Charkiv", "Metz", "Middlesbrough", "Midtjylland", "Milan", "Mlada Boleslav", "Molde", "Monaco", "München 1860", "Montpellier", "Moss", 
  "MTK Budapest", "Nacional de Madeira", "Nancy", "Nantes", "Napoli", "NEC Nijmegen", "Neftçi Baku", "Neuchâtel Xamax", "Newcastle Utd", "Nice", "NK Maribor", 
  "Nordsjælland", "Nürnberg", "Norrköping", "Norwich City", "Nottingham Forest", "NS Mura", "Obilić", "Odense", "OFĪ Krītī", "OFK Beograd", "Olimpija Ljubljana", 
  "Olympiakos", "Olympiakos Leukōsias", "Olympique Lyon", "Olympique Marseille", "Omonoia Leukōsias", "OPS", "Örgryte", "Osasuna", "Osijek", "Ankaraspor", "Östers IF", 
  "Oțelul Galați", "P'yownik", "Paços de Ferreira", "Palermo", "Panachaïkī", "Panathīnaïkos", "Pandurii Târgu Jiu", "Paniōnos", "PAOK Thessalonìki", "Paris Saint-Germain", 
  "Parma", "Partizan Beograd", "Partizani Tiranë", "Perugia", "Petrolul Ploiești", "Petrzalka", "Pezoporikos Larnaca", "Poli Timisoara", "Polonia Bytom", "Portadown", 
  "Porto", "Portsmouth", "Progres Niedercon", "Progresul Bucarest", "PSV Eindhoven", "Qairat", "Qarabag", "Qəbələ", "Queens Park Rangers", "Rabat Ajax", "Racing Santander", 
  "Radnicki Nis", "Raith Rovers", "Raków Częstochowa", "Randers", "Rangers", "Rapid Bucarest", "Rapid Wien", "Rayo Vallecano", "RB Lipsia", "Real Betis Siviglia", 
  "Real Madrid", "Real Sociedad", "Real Valladolid", "Red Boys Differdange", "Reipas Lahti", "Rennes", "RFC Liegi", "RFS Riga", "Rijeka", "Rio Ave", "Roda JC Kerkrade", 
  "Roma", "RoPS", "Rosenborg", "Rostov", "Rot-Weiss Erfurt", "Rot-Weiss Essen", "Rotor Volvograd", "Rubin Kazan", "Ruch Chorzow", "RWD Molenbeek", "Saarbrücken", 
  "Sachsen Leipzig", "Sachtar Donec'k", "Saint-Étienne", "Salzburg", "Sampdoria", "San Gallo", "Saragozza", "Sarajevo", "Sassuolo", "Schalke 04", "Servette", "Shahter FK", 
  "Shamrock Rovers", "Sheffield Wednesday", "Shelbourne", "Sheriff Tiraspol", "Sigma Olomouc", "Silkeborg", "Sion", "Sivasspor", "Sevilla", "Skeid", "Skënderbeu", "Skonto Riga", 
  "Slavia Praha", "Slavija-Mazyr", "Slesia Breslavia", "Sliema Wanderers", "Sligo Rovers", "Slovacko", "Slovan Bratislava", "Slovan Liberec", "Sochaux", "Southampton", 
  "Sparta Praha", "Sparta Rotterdam", "Spartak Mosca", "Spartak Plovdiv", "Spartak Trnava", "Spora Luxembourg", "Sporting Gijón", "Sporting Clube de Portugal", "Sportul Studentesc Bucarest", 
  "St Patrick's", "St. Johnstone", "St. Mirren", "Stade Dudelange", "Stade de Reims", "Stahl Brandeburgo", "Stal Mielec", "Standard Liège", "Start", "Steaua București", "Crvena Zvezda", 
  "Stuttgart", "Stoke City", "Strasbourg", "Stromsgodset", "Sturm Graz", "Swansea", "Swarovski Tirolo", "Szombierki Bytom", "Tatran Presov", "Tavriya Sinferopoli", "Tekstil'ščik Kamyšin", 
  "Tenerife", "Teplice", "Thun", "Tirolo Innsbruck", "Toulouse", "Torino", "Torpedo Moskva", "Tottenham", "TPS", "Trabzonspor", "Trelleborg FF", "Tromsø", "Twente", "U Craiova", 
  "Udinese", "Uerdingen", "Újpesti Dózsa", "Union Berlino", "Union Luxembourg", "Union Saint-Gilloise", "Unirea Urziceni", "UTA Arad", "Utrecht", "Vác", "Vaduz", "Valencia", "Vålerenga", 
  "Valletta", "Valur", "Vardar", "Vasas Budapest", "Vaslui", "Vejle", "Velez Mostar", "Ventspils", "Victoria Bucarest", "Viking", "Vikingur", "Frankfurter Viktoria", "Viktoria Plzen", 
  "Villareal", "Vistola Kraków", "Vitesse", "Vitkovice", "Vitoria Guimaraes", "Vitoria Setubal", "Vllaznia", "Vojvodina", "Vorskla", "VSS Kosice", "Wacker Innsbruck", "Waterford", 
  "Watford", "Werder Bremen", "West Bromwich", "West Ham", "Wettingen", "Widzew Lodz", "Wiener SK", "Wigan", "Willem II", "Winterslag", "Wolfsburg", "Wolverhampton", "Young Boys", 
  "Zaglebie Lubin", "Zaglebie Walbrzych", "Zalgiris", "Zalgiris Kaunas", "Zbrojovka Brno", "Zeljeznicar", "Zenit San Pietroburgo", "Zilina", "Zimbru Chișinău", "Zorja", "Zrinjski Mostar", 
  "Zulte Waregem", "Zürich"
];
  const teamInfo = {
  "Benfica":{flag:"https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg",
      colorsImg:"https://upload.wikimedia.org/wikipedia/commons/a/ac/Rosso_e_Bianco_con_aquila.svg"}
};
    const groups = [
      { prefix: "CL", label: "TotCL,CL,F,SF,Q,O,S,P,VS,DR", class: "cl-column" },
      { prefix: "EL", label: "TotEL,EL,F,SF,Q,O,S,P,VS,DR", class: "el-column" },
      { prefix: "CFL", label: "TotCFL,CFL,F,SF,Q,O,S,P,VS,DR", class: "cfl-column" },
      { prefix: "CWC", label: "TotCWC,CWC,F,SF,Q,O,S,P,VS,DR", class: "cwc-column" },
      { prefix: "SC", label: "TotSC,SC", class: "sc-column" },
    ];
    const columns = ["Tot", ...groups.flatMap(g => g.label.split(",").map(col => `${g.prefix}_${col}`))];
    const columnClasses = Object.fromEntries(columns.map(col => {
      if (col === "Tot") return [col, "tot"];
      const group = groups.find(g => col.startsWith(g.prefix));
      return [col, group ? group.class : ""];
    }));
    const data = {
      "1955/56": {
        "Real Madrid": { CL_CL: 1, CL_P:1, CL_VS:3, CL_DR:10 },
        "Milan": { CL_SF: 1, CL_P:1, CL_VS:1, CL_DR:6 },
        "Stade Reims": { CL_F: 1, CL_P:1, CL_VS:3, CL_DR:6},
          "Hibernian": { CL_SF: 1, CL_P:1, CL_VS:1, CL_DR:4},
"MTK Budapest": {CL_Q: 1, CL_P:1, CL_VS:1, CL_DR:4},
"Partinzan Beograd":{CL_Q: 1, CL_P:1, CL_VS:1, CL_DR:2},
"Djurgården":{CL_Q: 1, CL_P:1, CL_VS:-1, CL_DR:0},
"Rapid Wien":{CL_Q: 1, CL_P:1, CL_VS:-1, CL_DR:-1},
"Saarbrücken":{CL_O: 1, CL_P:1, CL_VS:0, CL_DR:-2}, 
"Aarhus":{CL_O: 1, CL_P:1, CL_VS:-1, CL_DR:-2},
"Sporting Clube de Portugal":{CL_O: 1, CL_P:1, CL_VS:-1, CL_DR:-3},
"Gwardia Warszawa":{CL_O: 1, CL_P:1, CL_VS:-1, CL_DR:-3},
"Rot-Weiss Essen":{CL_O: 1, CL_P:1, CL_VS:-1, CL_DR:-4},
"Anderlecht":{CL_O: 1, CL_P:1, CL_VS:-2, CL_DR:-6},
"Servette":{CL_O: 1, CL_P:1, CL_VS:-2, CL_DR:-7},
"PSV Eindhoven":{CL_O: 1, CL_P:1, CL_VS:0, CL_DR:-4}
      },
      "1956/57": {
        "Real Madrid": { CL_CL: 1, CL_P: 1, CL_VS:4, CL_DR:8},
        "Fiorentina": { CL_F: 1, CL_P: 1, CL_VS:2, CL_DR:2},
"Manchester United": { CL_SF: 1, CL_P: 1, CL_VS:2, CL_DR:12},
"Crvena Zvezda": { CL_SF: 1, CL_P: 1, CL_VS:1, CL_DR:3},
"Athletic Bilbao": { CL_Q: 1, CL_P: 1, CL_VS:3, CL_DR:2},
"CSKA Sofija": { CL_Q: 1, CL_P: 1, CL_VS:0, CL_DR:5},
"Grasshoppers": { CL_Q: 1, CL_P: 1, CL_VS:-1, CL_DR:-1},
"Nice": { CL_Q: 1, CL_P: 1, CL_VS:-2, CL_DR:-4},
"Slovan Bratislava": { CL_O: 1, CL_P: 1, CL_VS:0, CL_DR:1},
"Rapid Wien": { CL_O: 1, CL_P: 1, CL_VS:0, CL_DR:0},
"Rangers": { CL_O: 1, CL_P: 1, CL_VS:0, CL_DR:0},
"Honvéd Budapest": { CL_O: 1, CL_P: 1, CL_VS:-1, CL_DR:-1},
"Borussia Dortmund": { CL_O: 1, CL_P: 1, CL_VS:-1, CL_DR:-1},
"Norrköping": { CL_O: 1, CL_P: 1, CL_VS:-1, CL_DR:-1},
"Dinamo București": { CL_O: 1, CL_P: 1, CL_VS:0, CL_DR:-5},
"Roda JC Kerkrade": { CL_O: 1, CL_P: 1, CL_VS:-2, CL_DR:-3},
"Spora Luxembourg": { CL_P: 1, CL_VS:0, CL_DR:0},
"Galatasaray": { CL_P: 1, CL_VS:0, CL_DR:-1},
"Legia Warszawa": { CL_P: 1, CL_VS:0, CL_DR:-2},
"Aarhus": { CL_P: 1, CL_VS:-1, CL_DR:-4},
"Porto": { CL_P: 1, CL_VS:-2, CL_DR:-2},
"Anderlecht": { CL_P: 1, CL_VS:-2, CL_DR:-12}
      },
      "1957/58": {
  "Real Madrid": { CL_CL: 1, CL_P: 1, CL_VS: 4, CL_DR: 18 },
  "Milan": { CL_F: 1, CL_P: 1, CL_VS: 2, CL_DR: 10 },
  "Manchester United": { CL_SF: 1, CL_P: 1, CL_VS: 3, CL_DR: 7 },
  "Vasas Budapest": { CL_SF: 1, CL_P: 1, CL_VS: 2, CL_DR: 7 },
  "Crvena Zvezda": { CL_Q: 1, CL_P: 1, CL_VS: 2, CL_DR: 13 },
  "Ajax": { CL_Q: 1, CL_P: 1, CL_VS: 1, CL_DR: -1 },
  "Sevilla": { CL_Q: 1, CL_P: 1, CL_VS: 0, CL_DR: -4 },
  "Borussia Dortmund": { CL_Q: 1, CL_P: 1, CL_VS: -1, CL_DR: -3 },
  "Aarhus": { CL_O: 1, CL_P: 1, CL_VS: 1, CL_DR: 1 },
  "Steaua București": { CL_O: 1, CL_P: 1, CL_VS: 0, CL_DR: 0 },
  "Dukla Praha": { CL_O: 1, CL_P: 1, CL_VS: 0, CL_DR: -2 },
  "Young Boys": { CL_O: 1, CL_P: 1, CL_VS: -1, CL_DR: -1 },
  "Norrköping": { CL_O: 1, CL_P: 1, CL_VS: -1, CL_DR: -1 },
  "Erzgebirge Aue": { CL_O: 1, CL_P: 1, CL_VS: -2, CL_DR: -3 },
  "Rangers": { CL_O: 1, CL_P: 1, CL_VS: -2, CL_DR: -4 },
  "Royal Antwerp": { CL_O: 1, CL_P: 1, CL_VS: -2, CL_DR: -7 },
  "Gwardia Warszawa": { CL_P: 1, CL_VS: 0, CL_DR: 0 },
  "Saint-Étienne": { CL_P: 1, CL_VS: 0, CL_DR: -1 },
  "CSKA Sofija": { CL_P: 1, CL_VS: 0, CL_DR: -4},
  "Benfica": { CL_P: 1, CL_VS: -1, CL_DR: -2 },
  "Glenavon": { CL_P: 1, CL_VS: -1, CL_DR: -3 },
  "Shamrock Rovers": { CL_P: 1, CL_VS: -2, CL_DR: -7 },
  "Stade Dudelange": { CL_P: 1, CL_VS: -2, CL_DR: -13 },
  "Rapid Wien": { CL_P: 1, CL_VS: 0, CL_DR: 0 }
},
      "1958/59": {
  "Real Madrid": { CL_CL: 1, CL_P: 1, CL_VS: 3, CL_DR: 10 },
  "Stade de Reims": { CL_F: 1, CL_P: 1, CL_VS: 3, CL_DR: 15 },
  "Atlético Madrid": { CL_SF: 1, CL_P: 1, CL_VS: 3, CL_DR: 15 },
  "Young Boys": { CL_SF: 1, CL_P: 1, CL_VS: 2, CL_DR: 2 },
  "Standard Liège": { CL_Q: 1, CL_P: 1, CL_VS: 2, CL_DR: 6 },
  "Dukla Praha": { CL_O: 1, CL_P: 1, CL_VS: 1, CL_DR: 0 },
  "Chemnitzer": { CL_Q: 1, CL_P: 1, CL_VS: 1, CL_DR: 4 },
  "MTK Budapest": { CL_O: 1, CL_P: 1, CL_VS: 0, CL_DR: 2 },
  "Wiener SK": { CL_Q: 1, CL_P: 1, CL_VS: -1, CL_DR: 0 },
  "CSKA Sofija": { CL_O: 1, CL_P: 1, CL_VS: 0, CL_DR: 0 },
  "Schalke 04": { CL_Q: 1, CL_P: 1, CL_VS: 0, CL_DR: -2 },
  "Sporting Clube de Portugal": { CL_O: 1, CL_P: 1, CL_VS: 0, CL_DR: -2 },
  "Göteborg": { CL_O: 1, CL_P: 1, CL_VS: -1, CL_DR: -4 },
  "Wolverhampton": { CL_O: 1, CL_P: 1, CL_VS: -1, CL_DR: -1 },
  "Beşiktaş": { CL_O: 1, CL_P: 1, CL_VS: -1, CL_DR: -2 },
  "Dinamo Zagreb": { CL_P: 1, CL_VS: -1, CL_DR: -1 },
  "Juventus": { CL_P: 1, CL_VS: 0, CL_DR: -5 },
  "Manchester United": { CL_P: 1, CL_VS: 0, CL_DR: 0 },
  "Jeunesse Esch": { CL_P: 1, CL_VS: 0, CL_DR: 0 },
  "Olympiakos": { CL_P: 1, CL_VS: 0, CL_DR: 0 },
  "Kjøbenhavns BK": { CL_P: 1, CL_VS: 0, CL_DR: 0 },
  "Petrolul Ploiești": { CL_P: 1, CL_VS: 0, CL_DR: 0 },
  "Heart of Midlothian": { CL_P: 1, CL_VS: 0, CL_DR: -3 },
  "Polonia Bytom": { CL_P: 1, CL_VS: -2, CL_DR: -6 },
  "DOS Utrecht": { CL_P: 1, CL_VS: -2, CL_DR: -2 },
  "Ards": { CL_P: 1, CL_VS: -2, CL_DR: -7 },
  "Drumcondra": { CL_P: 1, CL_VS: -2, CL_DR: -12 },
  "HPS": { CL_P: 1, CL_VS: -2, CL_DR: -7 }
},
      "1959/60": {
  "Real Madrid": { CL_CL: 1, CL_P: 1, CL_VS: 5, CL_DR: 21 },
  "Eintracht Frankfurt": { CL_F: 1, CL_P: 1, CL_VS: 3, CL_DR: 8 },
  "Barcelona": { CL_SF: 1, CL_P: 1, CL_VS: 3, CL_DR: 13 },
  "Rangers": { CL_SF: 1, CL_P: 1, CL_VS: 4, CL_DR: 7 },
  "Nice": { CL_Q: 1, CL_P: 1, CL_VS: 2, CL_DR: 2 },
  "Wiener SK": { CL_Q: 1, CL_P: 1, CL_VS: 1, CL_DR: 3 },
  "Inter Bratislava": { CL_O: 1, CL_P: 1, CL_VS: 1, CL_DR: 2 },
  "Göteborg": { CL_O: 1, CL_P: 1, CL_VS: 0, CL_DR: 4 },
  "Sparta Rotterdam": { CL_Q: 1, CL_P: 1, CL_VS: 0, CL_DR: 1 },
  "Fenerbahçe": { CL_O: 1, CL_P: 1, CL_VS: 0, CL_DR: -3 },
  "Wolverhampton": { CL_Q: 1, CL_P: 1, CL_VS: -1, CL_DR: -3 },
  "Crvena Zvezda": { CL_O: 1, CL_P: 1, CL_VS: -1, CL_DR: -3 },
  "Young Boys": { CL_O: 1, CL_P: 1, CL_VS: -1, CL_DR: -3 },
  "B1909": { CL_O: 1, CL_P: 1, CL_VS: -1, CL_DR: -3 },
  "Milan": { CL_O: 1, CL_P: 1, CL_VS: -1, CL_DR: -4 },
  "Jeunesse Esch": { CL_O: 1, CL_P: 1, CL_VS: -2, CL_DR: -6 },
  "CSKA Sofija": { CL_P: 1, CL_VS: -1, CL_DR: -4 },
  "Petrolul Ploiești": { CL_P: 1, CL_VS: -1, CL_DR: -1 },
  "Csepel": { CL_P: 1, CL_VS: -1, CL_DR: -1 },
  "Shamrock Rovers": { CL_P: 1, CL_VS: -1, CL_DR: -1 },
  "Olympiakos": { CL_P: 1, CL_VS: -1, CL_DR: -2 },
  "Łódzki": { CL_P: 1, CL_VS: 0, CL_DR: -4 },
  "Linfield": { CL_P: 1, CL_VS: 0, CL_DR: -4 },
  "KuPS": { CL_P: 1, CL_VS: 0, CL_DR: 0 },
  "Frankfurter Viktoria": { CL_P: 1, CL_VS: 0, CL_DR: -1 },
  "Anderlecht": { CL_P: 1, CL_VS: -2, CL_DR: -5 },
  "Porto": { CL_P: 1, CL_VS: -2, CL_DR: -3 }
},
      "1960/61": {
  "Benfica": { CL_CL: 1, CL_P: 1, CL_VS: 6, CL_DR: 16 },
  "Barcelona": { CL_F: 1, CL_P: 1, CL_VS: 4, CL_DR: 10 },
  "Rapid Wien": { CL_SF: 1, CL_P: 1, CL_VS: 2, CL_DR: 5 },
  "Hamburger": { CL_SF: 1, CL_P: 1, CL_VS: 0, CL_DR: 5 },
  "IFK Malmö": { CL_Q: 1, CL_P: 1, CL_VS: 1, CL_DR: 0 },
  "Aarhus": { CL_Q: 1, CL_P: 1, CL_VS: 0, CL_DR: 1 },
  "Burnley": { CL_Q: 1, CL_P: 1, CL_VS: 0, CL_DR: 0 },
  "Hradec Králové": { CL_Q: 1, CL_P: 1, CL_VS: 0, CL_DR: -3 },
  "Stade de Reims": { CL_O: 1, CL_P: 1, CL_VS: 2, CL_DR: 9 },
  "Újpesti Dózsa": { CL_O: 1, CL_P: 1, CL_VS: 2, CL_DR: 1 },
  "Young Boys": { CL_O: 1, CL_P: 1, CL_VS: 1, CL_DR: 2 },
  "CSKA Sofija": { CL_O: 1, CL_P: 1, CL_VS: -1, CL_DR: 0 },
  "Erzgebirge Aue": { CL_O: 1, CL_P: 1, CL_VS: -1, CL_DR: -1 },
  "Real Madrid": { CL_O: 1, CL_P: 1, CL_VS: -1, CL_DR: -1 },
  "Panathīnaïkos": { CL_O: 1, CL_P: 1, CL_VS: -1, CL_DR: -1 },
  "Fredrikstad": { CL_O: 1, CL_P: 1, CL_VS: -1, CL_DR: -3 },
  "Glenavon": { CL_P: 1, CL_VS: 0, CL_DR: 0 },
  "Steaua București": { CL_P: 1, CL_VS: 0, CL_DR: 0 },
  "Juventus": { CL_P: 1, CL_VS: 0, CL_DR: -1 },
  "Legia Warszawa": { CL_P: 1, CL_VS: 0, CL_DR: -2 },
  "Beşiktaş": { CL_P: 1, CL_VS: 0, CL_DR: -3 },
  "Ajax": { CL_P: 1, CL_VS: -1, CL_DR: -1 },
  "HIFK": { CL_P: 1, CL_VS: -2, CL_DR: -3 },
  "Heart of Midlothian": { CL_P: 1, CL_VS: -2, CL_DR: -4 },
  "Crvena Zvezda": { CL_P: 1, CL_VS: -2, CL_DR: -4 },
  "Lierse": { CL_P: 1, CL_VS: -2, CL_DR: -5 },
  "Limerick": { CL_P: 1, CL_VS: -2, CL_DR: -7 },
  "Jeunesse Esch": { CL_P: 1, CL_VS: -2, CL_DR: -10 }
},
      "1961/62": {
        "Fenerbahçe": {CL_O:1, CL_P:1, CL_VS:-2, CL_DR:-2},
        "Benfica": {CL_CL:1, CL_P:1, CL_VS:2, CL_DR:11},
        "Real Madrid": {CL_F:1, CL_P:1, CL_VS:6, CL_DR:22},
        "Tottenham": {CL_SF:1, CL_P:1, CL_VS:1, CL_DR:8},
        "Standard Liège": {CL_SF:1, CL_P:1, CL_VS:2, CL_DR:4},
        "Nürnberg": {CL_Q:1, CL_P:1, CL_VS:4, CL_DR:6},
        "Rangers": {CL_Q:1, CL_P:1, CL_VS:4, CL_DR:5},
        "Juventus": {CL_Q:1, CL_P:1, CL_VS:2, CL_DR:5},
        "Dukla Praha": {CL_Q:1, CL_P:1, CL_VS:1, CL_DR:0},
        "Servette": {CL_O:1, CL_P:1, CL_VS:2, CL_DR:5},
        "B1913": {CL_O:1, CL_P:1, CL_VS:0, CL_DR:1},
        "Austria Wien": {CL_O:1, CL_P:1, CL_VS:0, CL_DR:-2},
        "Frankfurter Viktoria": {CL_O:1, CL_P:1, CL_VS:-1, CL_DR:-1},
        "Partizan Beograd": {CL_O:1, CL_P:1, CL_VS:-1, CL_DR:-4},
        "Haka": {CL_O:1, CL_P:1, CL_VS:-2, CL_DR:-6},
        "Feyenoord": {CL_O:1, CL_P:1, CL_VS:1, CL_DR:7},
        "CSKA Sofija": {CL_P:1, CL_VS:-1, CL_DR:-1},
        "Panathīnaïkos": {CL_P:1, CL_VS:-1, CL_DR:-1},
        "Steaua București": {CL_P:1, CL_VS:-1, CL_DR:-2},
        "Górnik Zabrze": {CL_P:1, CL_VS:0, CL_DR:-5},
        "Sporting Clube de Portugal": {CL_P:1, CL_VS:-1, CL_DR:-2},
        "Linfield": {CL_P:1, CL_VS:-1, CL_DR:-3},
        "Monaco": {CL_P:1, CL_VS:-2, CL_DR:-2},
        "Fredrikstad": {CL_P:1, CL_VS:-2, CL_DR:-3},
        "Vasas Budapest": {CL_P:1, CL_VS:-2, CL_DR:-4},
        "Hibernians": {CL_P:1, CL_VS:-2, CL_DR:-6},
        "Drumcondra": {CL_P:1, CL_VS:-2, CL_DR:-8},
        "Göteborg": {CL_P:1, CL_VS:-2, CL_DR:-9},
        "Spora Luxembourg": {CL_P:1, CL_VS:-2, CL_DR:-13}
      },
      "1962/63": {
  "Milan": { CL_CL: 1, CL_P: 1, CL_VS: 5, CL_DR: 27 },
  "Benfica": { CL_F: 1, CL_P: 1, CL_VS: 2, CL_DR: 6 },
  "Dundee FC": { CL_SF: 1, CL_P: 1, CL_VS: 2, CL_DR: 6 },
  "Feyenoord": { CL_SF: 1, CL_P: 1, CL_VS: 2, CL_DR: 2 },
  "Dukla Praha": { CL_Q: 1, CL_P: 1, CL_VS: 2, CL_DR: 8 },
  "Stade de Reims": { CL_Q: 1, CL_P: 1, CL_VS: -1, CL_DR: 3 },
  "Anderlecht": { CL_Q: 1, CL_P: 1, CL_VS: 0, CL_DR: -1 },
  "Galatasaray": { CL_Q: 1, CL_P: 1, CL_VS: -1, CL_DR: -2 },
  "Ipswich Town": { CL_O: 1, CL_P: 1, CL_VS: 2, CL_DR: 11 },
  "Vasas Budapest": { CL_O: 1, CL_P: 1, CL_VS: 1, CL_DR: 9 },
  "Sporting Clube de Portugal": { CL_O: 1, CL_P: 1, CL_VS: 2, CL_DR: 4 },
  "Polonia Bytom": { CL_O: 1, CL_P: 1, CL_VS: 2, CL_DR: 2 },
  "Austria Wien": { CL_O: 1, CL_P: 1, CL_VS: 2, CL_DR: 0 },
  "CSKA Sofija": { CL_O: 1, CL_P: 1, CL_VS: 1, CL_DR: 2 },
  "Norrköping": { CL_O: 1, CL_P: 1, CL_VS: 0, CL_DR: -2 },
  "Esbjerg": { CL_O: 1, CL_P: 1, CL_VS: 0, CL_DR: -4 },
  "Köln": { CL_P: 1, CL_VS: 0, CL_DR: -3 },
  "Real Madrid": { CL_P: 1, CL_VS: -1, CL_DR: -1 },
  "Linfield": { CL_P: 1, CL_VS: -1, CL_DR: -1 },
  "Servette": { CL_P: 1, CL_VS: -1, CL_DR: -2 },
  "Partizani Tiranë": { CL_P: 1, CL_VS: -1, CL_DR: -2 },
  "Dinamo București": { CL_P: 1, CL_VS: -1, CL_DR: -3 },
  "Panathīnaïkos": { CL_P: 1, CL_VS: -2, CL_DR: -4 },
  "Partizan Beograd": { CL_P: 1, CL_VS: -2, CL_DR: -4 },
  "HIFK": { CL_P: 1, CL_VS: -2, CL_DR: -4 },
  "Frankfurter Viktoria": { CL_P: 1, CL_VS: -2, CL_DR: -4 },
  "Shelbourne": { CL_P: 1, CL_VS: -2, CL_DR: -6 },
  "Fredrikstad": { CL_P: 1, CL_VS: -2, CL_DR: -10 },
  "Floriana": { CL_P: 1, CL_VS: -2, CL_DR: -13 },
  "Union Luxembourg": { CL_P: 1, CL_VS: -2, CL_DR: -14 }
},
      "1963/64": {
      "Internazionale Milano": {CL_CL:1, CL_P: 1, CL_VS:7, CL_DR:11},
      "Real Madrid": {CL_F:1, CL_P: 1, CL_VS:5, CL_DR:17},  
      "Borussia Dortmund": {CL_SF:1, CL_P: 1, CL_VS:1, CL_DR:8},
      "Zürich": {CL_SF:1, CL_P: 1, CL_VS:-2, CL_DR:-4},
      "PSV Eindhoven": {CL_Q:1, CL_P: 1, CL_VS:3, CL_DR:7},
      "Dukla Praha": {CL_Q:1, CL_P: 1, CL_VS:2, CL_DR:7}, 
      "Partizan Beograd": {CL_Q:1, CL_P: 1, CL_VS:0, CL_DR:5}, 
      "Milan" : {CL_Q:1, CL_P: 1, CL_VS:1, CL_DR:2}, 
      "Benfica": {CL_O:1, CL_P: 1, CL_VS:1, CL_DR:1}, 
      "Górnik Zabrze": {CL_O:1, CL_P: 1, CL_VS:1, CL_DR:0},   
      "Galatasaray": {CL_O:1, CL_P: 1, CL_VS:0, CL_DR:2},
      "Monaco": {CL_O:1, CL_P: 1, CL_VS:-1, CL_DR:2},  
      "Dinamo București" : {CL_O:1, CL_P: 1, CL_VS:0, CL_DR:-1},
      "Jeunesse Esch" : {CL_O:1, CL_P: 1, CL_VS:0, CL_DR:-2},  
      "Spartak Plovdiv" : {CL_O:1, CL_P: 1, CL_VS:-1, CL_DR:0}, 
      "Norrköping": {CL_O:1, CL_P: 1, CL_VS:-1, CL_DR:-2}, 
      "Haka"  : {CL_P: 1, CL_VS:0, CL_DR:-1},
      "Partizani Tiranë": {CL_P: 1, CL_VS:0, CL_DR:-1}, 
      "Standard Liège" : {CL_P: 1, CL_VS:0, CL_DR:-1},
      "Dundalk" : {CL_P: 1, CL_VS:0, CL_DR:-2},  
      "Ferencváros"  : {CL_P: 1, CL_VS:0, CL_DR:-2},
      "Austria Wien" : {CL_P: 1, CL_VS:-1, CL_DR:-1},
      "Everton" : {CL_P: 1, CL_VS:-1, CL_DR:-1}, 
      "Lisburn Distillery" : {CL_P: 1, CL_VS:-1, CL_DR:-5},
      "AEK Athīna" : {CL_P: 1, CL_VS:-1, CL_DR:-5}, 
      "Carl Zeiss Jena" : {CL_P: 1, CL_VS:-2, CL_DR:-3},
      "Lyn Oslo" : {CL_P: 1, CL_VS:-2, CL_DR:-4}, 
      "Anorthōsī Ammochōstou"   : {CL_P: 1, CL_VS:-2, CL_DR:-5},   
      "Esbjerg" : {CL_P: 1, CL_VS:-2, CL_DR:-7}, 
      "Rangers" : {CL_P: 1, CL_VS:-2, CL_DR:-7},
      "Valletta" : {CL_P: 1, CL_VS:-2, CL_DR:-8}             
    },
      "1964/65": {
"Glentoran": {CL_P: 1, CL_VS:-1, CL_DR:-1},
      "Panathīnaïkos": {CL_O:1, CL_P: 1, CL_VS:0, CL_DR:0},  
  "Partizani Tiranë": {CL_P: 1, CL_VS:-1, CL_DR:-2},
      "Köln": {CL_Q:1, CL_P: 1, CL_VS:2, CL_DR:3},
      "KR Reykjavík": {CL_P: 1, CL_VS:-2, CL_DR:-10},
      "Liverpool": {CL_SF:1, CL_P: 1, CL_VS:4, CL_DR:13}, 
      "Anderlecht": {CL_O:1, CL_P: 1, CL_VS:-2, CL_DR:-4}, 
      "Bologna" : {CL_P: 1, CL_VS:0, CL_DR:0}, 
      "Internazionale Milano": {CL_CL:1, CL_P: 1, CL_VS:4, CL_DR:10}, 
      "Sliema Wanderers": {CL_P: 1, CL_VS:-2, CL_DR:-7},   
      "Dinamo București": {CL_O:1, CL_P: 1, CL_VS:0, CL_DR:2},
      "Rangers": {CL_Q:1, CL_P: 1, CL_VS:3, CL_DR:4},  
      "Crvena Zvezda" : {CL_P: 1, CL_VS:-1, CL_DR:-2},
      "Rapid Wien" : {CL_O:1, CL_P: 1, CL_VS:0, CL_DR:2},  
      "Shamrock Rovers" : {CL_P: 1, CL_VS:-2, CL_DR:-5}, 
      "DWS": {CL_Q:1, CL_P: 1, CL_VS:3, CL_DR:9}, 
      "Fenerbahçe"  : {CL_P: 1, CL_VS:-2, CL_DR:-3},
      "Reipas Lahti": {CL_P: 1, CL_VS:0, CL_DR:-2}, 
      "Lyn Oslo" : {CL_O:1, CL_P: 1, CL_VS:-2, CL_DR:-5},
      "Sachsen Leipzig" : {CL_P: 1, CL_VS:-2, CL_DR:-4},  
      "Győr"  : {CL_SF: 1, CL_P: 1, CL_VS:1, CL_DR:1},
      "Lokomotiv Sofija" : {CL_O:1, CL_P: 1, CL_VS:0, CL_DR:2},
      "Malmö FF" : {CL_P: 1, CL_VS:0, CL_DR:-3}, 
      "Saint-Étienne" : {CL_P: 1, CL_VS:-1, CL_DR:-1},
      "La Chaux-de-Fonds" : {CL_O:1, CL_P: 1, CL_VS:0, CL_DR:-4}, 
      "Aris Bonnevoie" : {CL_P: 1, CL_VS:-2, CL_DR:-8},
      "Benfica" : {CL_F:1, CL_P: 1, CL_VS:4, CL_DR:20}, 
      "B1909"   : {CL_P: 1, CL_VS:-2, CL_DR:-7},   
      "Real Madrid" : {CL_Q:1, CL_P: 1, CL_VS:3, CL_DR:8}, 
      "Dukla Praha" : {CL_O:1, CL_P: 1, CL_VS:-1, CL_DR:-4},
      "Górnik Zabrze" : {CL_P: 1, CL_VS:0, CL_DR:0}             
    },
      "1965/66": {
      "Fenerbahçe": {CL_P: 1, CL_VS:-1, CL_DR:-4},
      "Anderlecht": {CL_Q:1, CL_P: 1, CL_VS:2, CL_DR:12},  
"Lyn Oslo": {CL_P: 1, CL_VS:0, CL_DR:-2},
"Derry City":{CL_O:1,CL_P:1,CL_VS:-1, CL_DR:-7},
"KF Tiranë": {CL_P: 1, CL_VS:-1, CL_DR:-1},
"Kilmarnock":{CL_O:1,CL_P: 1,CL_VS:0, CL_DR:-3}, 
"Real Madrid":{CL_CL:1,CL_P:1,CL_VS:3, CL_DR:11}, 
"Feyenoord" : {CL_P: 1, CL_VS:0, CL_DR:-4}, 
"Dinamo București": {CL_O:1, CL_P: 1, CL_VS:2, CL_DR:4}, 
"B1909": {CL_P: 1, CL_VS:-2, CL_DR:-5},   
"Internazionale Milano": {CL_SF:1, CL_P: 1, CL_VS:0, CL_DR:4},
"Keflavík": {CL_P: 1, CL_VS:-2, CL_DR:-11},  
"Ferencváros":{CL_Q:1,CL_P:1, CL_VS:2, CL_DR:9},
"Panathīnaïkos":{CL_O:1,CL_P:1,CL_VS:-1, CL_DR:0},  
"Sliema Wanderers":{CL_P: 1, CL_VS:0, CL_DR:-2}, 
"Lausanne": {CL_P: 1, CL_VS:-1, CL_DR:-4}, 
"Sparta Praha": {CL_Q:1, CL_P: 1, CL_VS:3, CL_DR:6},
"LASK": {CL_P: 1, CL_VS:-2, CL_DR:-3}, 
"Górnik Zabrze":{CL_O:1,CL_P:1,CL_VS:0, CL_DR:-1},
"Partizan Beograd":{CL_F:1,CL_P:1,CL_VS:0, CL_DR:6},  
"Nantes"  : {CL_P:1, CL_VS:-1, CL_DR:-2},
"Apoel" : {CL_P: 1, CL_VS:-2, CL_DR:-10},
"Werder Bremen":{CL_O:1,CL_P:1,CL_VS:2, CL_DR:8}, 
"Drumcondra" : {CL_P: 1, CL_VS:0, CL_DR:-2},
"Frankfurter Viktoria" : {CL_O:1, CL_P: 1, CL_VS:-2, CL_DR:-2}, 
"HJK" : {CL_P: 1, CL_VS:-2, CL_DR:-7},
"Manchester United" : {CL_SF:1, CL_P: 1, CL_VS:6, CL_DR:15}, 
"Djurgården" : {CL_P: 1, CL_VS:0, CL_DR:-5},   
"Levski Sofija":{CL_O:1,CL_P:1,CL_VS:-1, CL_DR:4}, 
"Stade Dudelange":{CL_P:1,CL_VS:-2, CL_DR:-18},
"Benfica" : {CL_Q:1, CL_P: 1, CL_VS:1, CL_DR:14}             
    },
    "1966/67": {
"Admira Wien":{CL_P: 1, CL_VS:-1, CL_DR:-1},
"Vojvodina":{CL_Q:1,CL_P:1,CL_VS:2, CL_DR:1},  
"Malmö FF": {CL_P: 1, CL_VS:-2, CL_DR:-4},
"Atlético Madrid":{CL_O:1,CL_P:1,CL_VS:1, CL_DR:3},
"KR Reykjavík": {CL_P: 1, CL_VS:-2, CL_DR:-4},
"Nantes": {CL_O:1, CL_P: 1, CL_VS:0, CL_DR:0}, 
"Celtic":{CL_CL:1, CL_P: 1, CL_VS:6, CL_DR:13}, 
"Zürich" : {CL_P: 1, CL_VS:-2, CL_DR:-5}, 
"Ajax": {CL_Q:1, CL_P: 1, CL_VS:2, CL_DR:6}, 
"Beşiktaş": {CL_P: 1, CL_VS:-2, CL_DR:-3},   
"Liverpool":{CL_O:1,CL_P:1, CL_VS:0, CL_DR:-2},
"Petrolul Ploiești":{CL_P:1,CL_VS:-1, CL_DR:-2},  
"Esbjerg" : {CL_P: 1, CL_VS:-2, CL_DR:-6},
"Dukla Praha":{CL_SF:1,CL_P:1,CL_VS:4,CL_DR:9},  
"Haka":{CL_P:1,CL_VS:-2,CL_DR:-11}, 
"Anderlecht":{CL_O:1,CL_P:1,CL_VS:0,CL_DR:7}, 
"Internazionale Milano":{CL_F:1,CL_P:1,CL_VS:5, CL_DR:7},
"Torpedo Moskva":{CL_P: 1, CL_VS:-1, CL_DR:-1}, 
"Vasas Budapest":{CL_O:1, CL_P: 1, CL_VS:0, CL_DR:4},
"Sporting Clube de Portugal":{CL_P:1,CL_VS:-2, CL_DR:-7},  
"München 1860":{CL_O:1,CL_P:1,CL_VS:2,CL_DR:8},
"Omonoia Leukōsias":{CL_P:1,CL_VS:-2,CL_DR:-9},
"Real Madrid":{CL_Q:1,CL_P:1,CL_VS:-2,CL_DR:-2}, 
"Vålerenga":{CL_O:1,CL_P:1,CL_VS:-1,CL_DR:-3},
"KF Tiranë" : {CL_P: 1, CL_VS:0, CL_DR:0}, 
"Aris Bonnevoie":{CL_P: 1, CL_VS:-1, CL_DR:-5},
"Linfield":{CL_Q:1, CL_P: 1, CL_VS:1, CL_DR:7}, 
"CSKA Sofija":{CL_SF:1,CL_VS:0,CL_DR:2},     "Olympiakos" : {CL_P: 1, CL_VS:0, CL_DR:-1}, 
"Górnik Zabrze":{CL_O:1,CL_P:1,CL_VS:1,CL_DR:1},
"Frankfurter Viktoria":{CL_P:1,CL_VS:-1,CL_DR:-2}             
}
};
